package cn.powerdash.libsystem.book.domain;
// Generated 2017-3-2 0:17:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePermissionId generated by hbm2java
 */
@Embeddable
public class RolePermissionId implements java.io.Serializable {

	private String rolename;
	private String permission;

	public RolePermissionId() {
	}

	public RolePermissionId(String rolename, String permission) {
		this.rolename = rolename;
		this.permission = permission;
	}

	@Column(name = "ROLENAME", nullable = false, length = 25)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "PERMISSION", nullable = false, length = 25)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePermissionId))
			return false;
		RolePermissionId castOther = (RolePermissionId) other;

		return ((this.getRolename() == castOther.getRolename()) || (this.getRolename() != null
				&& castOther.getRolename() != null && this.getRolename().equals(castOther.getRolename())))
				&& ((this.getPermission() == castOther.getPermission())
						|| (this.getPermission() != null && castOther.getPermission() != null
								&& this.getPermission().equals(castOther.getPermission())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRolename() == null ? 0 : this.getRolename().hashCode());
		result = 37 * result + (getPermission() == null ? 0 : this.getPermission().hashCode());
		return result;
	}

}
