package cn.powerdash.libsystem.book.domain;
// Generated 2017-3-16 22:45:37 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Storagehistory generated by hbm2java
 */
@Entity
@Table(name = "storagehistory", catalog = "libsystem")
public class Storagehistory implements java.io.Serializable {

	private Integer id;
	private int bookid;
	private int dealType;
	private Date dealDate;
	private int storeId;

	public Storagehistory() {
	}

	public Storagehistory(int bookid, int dealType, Date dealDate, int storeId) {
		this.bookid = bookid;
		this.dealType = dealType;
		this.dealDate = dealDate;
		this.storeId = storeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bookid", nullable = false)
	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	@Column(name = "deal_type", nullable = false)
	public int getDealType() {
		return this.dealType;
	}

	public void setDealType(int dealType) {
		this.dealType = dealType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deal_date", nullable = false, length = 10)
	public Date getDealDate() {
		return this.dealDate;
	}

	public void setDealDate(Date dealDate) {
		this.dealDate = dealDate;
	}

	@Column(name = "store_id", nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

}
