package cn.powerdash.libsystem.book.domain;
// Generated 2017-3-2 0:17:49 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "libsystem")
public class User implements java.io.Serializable {

	private String username;
	private String password;
	private String name;
	private String status;
	private Integer loginFailureCt;
	private Date lastLoginTs;
	private Date lastLoginFailureTs;
	private Set<Role> roles = new HashSet<Role>(0);

	public User() {
	}

	public User(String username, String password, String status, Date lastLoginTs, Date lastLoginFailureTs) {
		this.username = username;
		this.password = password;
		this.status = status;
		this.lastLoginTs = lastLoginTs;
		this.lastLoginFailureTs = lastLoginFailureTs;
	}

	public User(String username, String password, String name, String status, Integer loginFailureCt, Date lastLoginTs,
			Date lastLoginFailureTs, Set<Role> roles) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.status = status;
		this.loginFailureCt = loginFailureCt;
		this.lastLoginTs = lastLoginTs;
		this.lastLoginFailureTs = lastLoginFailureTs;
		this.roles = roles;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 25)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "login_failure_ct")
	public Integer getLoginFailureCt() {
		return this.loginFailureCt;
	}

	public void setLoginFailureCt(Integer loginFailureCt) {
		this.loginFailureCt = loginFailureCt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_ts", nullable = false, length = 19)
	public Date getLastLoginTs() {
		return this.lastLoginTs;
	}

	public void setLastLoginTs(Date lastLoginTs) {
		this.lastLoginTs = lastLoginTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_failure_ts", nullable = false, length = 19)
	public Date getLastLoginFailureTs() {
		return this.lastLoginFailureTs;
	}

	public void setLastLoginFailureTs(Date lastLoginFailureTs) {
		this.lastLoginFailureTs = lastLoginFailureTs;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "USER_ROLE", catalog = "libsystem", joinColumns = {
			@JoinColumn(name = "USERNAME", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "ROLENAME", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
